replicaCount: 1
image:
  repository: peishu/currencyservice
  tag: 235872c17f9263392805b6c919aeac5935816106
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 7000
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
